language: generic
sudo: false
dist: xenial
jdk: openjdk8

env:
  global:
    BYOND_MAJOR="512"
    BYOND_MINOR="1467"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
matrix:
    include:
    - name: "Code"
      env: TEST=CODE
    - name: "Web"
      env: TEST=WEB
    - name: "Map - Nexus"
      env: TEST=MAP MAP_PATH=nexus

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip
      - uchardet

script:
  - test/run-test.sh