language: generic
sudo: false
dist: trusty

env:
  global:
    BYOND_MAJOR="512"
    BYOND_MINOR="1453"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
  matrix:
    - TEST=CODE
    - TEST=WEB
    - TEST=MAP MAP_PATH=vignette

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

before_install:
    - unset _JAVA_OPTIONS

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - oracle-java8-set-default
      - python
      - python-pip

script:
  - test/run-test.sh
