/decl/cultural_info/culture/phorosian
	name = CULTURE_PHOROSIAN
	language = LANGUAGE_GALCOM
	description = "#TODO_PHOROSIAN \
	"
	secondary_langs = list(LANGUAGE_HUMAN_EURO, LANGUAGE_SIGN, LANGUAGE_GUTTER, LANGUAGE_HUMAN_ARABIC, LANGUAGE_HUMAN_CHINESE, LANGUAGE_HUMAN_IBERIAN, LANGUAGE_HUMAN_INDIAN, LANGUAGE_HUMAN_RUSSIAN, LANGUAGE_SPACER)

