#define MUSIC_GENRE_ACTION "ACTION"
#define MUSIC_GENRE_DARK "DARK"
#define MUSIC_GENRE_AMBIENT "AMBIENT"
#define MUSIC_GENRE_NEUTRAL "NEUTRAL"

#define MUSIC_GENRE_ASTEROID_1 "ASTEROID_1"
#define MUSIC_GENRE_ASTEROID_2 "ASTEROID_2"
#define MUSIC_GENRE_ASTEROID_3 "ASTEROID_3"
#define MUSIC_GENRE_ASTEROID_4 "ASTEROID_4"
