#define MESSAGE_MODE_WHISPER      "whisper"
#define MESSAGE_MODE_HEADSET      "headset"
#define MESSAGE_MODE_RADIO_CUSTOM "radio_custom"
#define MESSAGE_MODE_DEPARTMENT   "department"
#define MESSAGE_MODE_GENERAL      "general"
#define MESSAGE_MODE_LEFT_EAR     "left ear"
#define MESSAGE_MODE_RIGHT_EAR    "right ear"
#define MESSAGE_MODE_INTERCOM     "intercom"